name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Lint and Test
    
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      # Run ESLint
      - run: npm run lint

      # Run Jest
      - run: npm run test
